import config from './config.js';
import {escapeHtml as e} from './mail.js';

export const formFields=()=>config.fields.map(field=>{
  const common=`name="${e(field.name)}" required maxlength="${field.type==='textarea'?2000:300}"`;
  if(field.type==='checkbox')return `<label class="check"><input type="checkbox" name="${e(field.name)}" required> <span>${e(field.label)}</span></label>`;
  let control;
  if(field.type==='textarea')control=`<textarea ${common} rows="4"></textarea>`;
  else if(field.options)control=`<select ${common}><option value="">Choose an option</option>${field.options.map(o=>`<option value="${e(o.value)}">${e(o.label)}</option>`).join('')}</select>`;
  else control=`<input ${common} type="${e(field.type)}" autocomplete="${field.name==='email'?'email':field.name==='name'?'name':'off'}">`;
  return `<label><span>${e(field.label)}</span>${control}</label>`;
}).join('');
export const detailsHtml=()=>config.details.map(([key,value])=>`<div class="detail"><small>${e(key)}</small><strong>${e(value)}</strong></div>`).join('');
export const rowsHtml=rows=>rows.map(row=>`<article class="list-item"><h3>${e(row.title)}</h3><p>${e(row.description)}</p></article>`).join('');
export function layout(title,body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="referrer" content="no-referrer"><title>${e(title)} · ${e(config.title)}</title><link rel="stylesheet" href="/style.css"><link rel="icon" href="/favicon.svg"></head><body><header class="site-header"><a class="wordmark" href="/">${e(config.title)}</a><a class="quiet-link" href="/admin">Operator</a></header><main>${body}</main><footer>Small tools, useful work. <span>${e(config.framework)}</span></footer></body></html>`;
}
export function homeHtml(model,message='',error='') {
  const overview=`<div class="eyebrow">${e(config.eyebrow)}</div><h1>${e(config.headline)}</h1><p class="intro">${e(config.description)}</p><div class="details">${detailsHtml()}</div>${Number.isInteger(model.remaining)?`<p class="count">${model.remaining} of ${config.capacity} seats available</p>`:config.kind==='rsvp'?`<p class="count">${model.count} people on the list</p>`:''}${config.projects.map(([title,desc])=>`<article class="project"><span>Sample project</span><h3>${e(title)}</h3><p>${e(desc)}</p></article>`).join('')}`;
  const feedback=`${message?`<div role="status" class="notice">${e(message)}</div>`:''}${error?`<div role="alert" class="notice error">${e(error)}</div>`:''}`;
  const form=config.hideForm?'<div class="card"><h2>Your private quote link</h2><p>The project owner creates and shares your quote link from the operator page.</p></div>':`<form class="card" method="post" action="/api/submit"><h2>${e(config.button)}</h2>${feedback}${formFields()}<button>${e(config.button)}</button><p class="form-note">${e(config.formNote)}</p></form>`;
  return layout(config.title,`<section class="hero"><div>${overview}</div>${form}</section>${model.rows.length?`<section class="listing"><h2>${config.kind==='share'?'In this collection':'The idea board'}</h2>${rowsHtml(model.rows)}</section>`:''}`);
}
export function adminHtml(model,message='',extraUrl='') {
  let controls='';
  if(config.kind==='share')controls=`<form class="card compact" method="post" action="/api/admin"><h2>Add a bookmark</h2><input type="hidden" name="action" value="add_bookmark"><label>Title<input name="title" maxlength="120" required></label><label>URL<input type="url" name="url" required></label><button>Add bookmark</button></form>`;
  if(config.kind==='quote')controls=`<form method="post" action="/api/admin"><input type="hidden" name="action" value="create_quote"><button>Create a private quote link</button></form>`;
  if(config.kind==='subscriber')controls=`<form class="card compact" method="post" action="/api/admin"><h2>Send project notes</h2><input type="hidden" name="action" value="send_newsletter"><label>Unique edition key<input name="edition" pattern="[a-z0-9][a-z0-9-]{0,63}" maxlength="64" placeholder="october-notes" required></label><label>Subject<input name="subject" maxlength="150" required></label><label>Message<textarea name="body" rows="5" maxlength="4000" required></textarea></label><p>Only confirmed subscribers receive an edition. Reusing its key cannot send it twice. Up to 100 subscribers.</p><button>Send to confirmed subscribers</button></form>`;
  const entries=model.records.map(row=>`<article class="admin-row"><div><span class="status">${e(row.status)}</span><h3>${e(row.data.title || row.data.name || row.data.item || 'Request')}</h3><p>${e(row.email)}</p><dl>${Object.entries(row.data).filter(([key])=>!['email','name'].includes(key)).map(([key,value])=>`<div><dt>${e(key.replaceAll('_',' '))}</dt><dd>${e(value)}</dd></div>`).join('')}</dl><small>Reference ${e(row.id)}</small></div>${row.status==='pending'?`<form method="post" action="/api/admin"><input type="hidden" name="id" value="${e(row.id)}">${config.actions.map(([action,label])=>`<button name="action" value="${e(action)}">${e(label)}</button>`).join('')}</form>`:''}</article>`).join('');
  const mail=model.outbox.map(item=>`<tr><td>${e(item.id)}<br>${e(item.provider_id || '')}</td><td>${e(item.status)}</td><td>${e(item.error || (item.status==='accepted'?'Accepted by email provider; delivery not confirmed.':item.status==='logged'?'Recorded locally. No email was sent.':''))}</td></tr>`).join('');
  return layout('Operator',`<section class="operator"><div class="eyebrow">WORKSPACE</div><h1>Manage ${e(config.title.toLowerCase())}.</h1>${message?`<p class="notice" role="status">${e(message)}</p>`:''}${extraUrl?`<p class="notice">Private link: <a href="${e(extraUrl)}">${e(extraUrl)}</a></p>`:''}${controls}<h2>Editions</h2>${model.extra.editions.map(row=>`<p>${e(row.data.edition)} — ${e(row.data.subject)}</p>`).join('') || '<p>No editions yet.</p>'}<h2>Recent records</h2>${entries || '<p class="muted">No records yet. Complete the form to get started.</p>'}<h2>Email status</h2><p class="muted">Failed messages can be retried with <code>npm run retry-email</code>. Reconcile unknown or interrupted sends with provider logs first.</p><div class="table-wrap"><table><thead><tr><th>Outbox / provider reference</th><th>State</th><th>Details</th></tr></thead><tbody>${mail || '<tr><td colspan="3">No emails queued.</td></tr>'}</tbody></table></div></section>`);
}
export function accessHtml(grant) {
  if(grant.action==='view')return layout('Shared collection',`<section class="operator"><div class="eyebrow">SHARED READING</div><h1>A collection for you.</h1>${JSON.parse(grant.description).map(item=>`<article class="list-item"><a href="${e(item.url)}" rel="noreferrer">${e(item.title)}</a><p>${e(item.url)}</p></article>`).join('')}</section>`);
  const choices=grant.action==='quote_decision'?'<button name="decision" value="accept">Accept quote</button><button class="secondary" name="decision" value="decline">Decline quote</button>':`<button>${grant.action==='download'?'Download checklist':grant.action==='unsubscribe'?'Unsubscribe':grant.action==='confirm_subscription'?'Confirm subscription':'Accept invitation'}</button>`;
  return layout('Your link',`<section class="operator narrow"><div class="eyebrow">${e(config.title)}</div><h1>One more step.</h1><p class="intro">${e(grant.description)}</p><form method="post" action="/api/redeem"><input type="hidden" name="token" value="${e(grant.token)}">${choices}</form><p class="muted">Opening this page does not use your link. Your action is confirmed when you press the button.</p></section>`);
}
export const messageHtml=(message,isError=false)=>layout(isError?'Unable to continue':'All set',`<section class="operator narrow"><h1>${isError?'Unable to continue.':'All set.'}</h1><p class="intro" role="${isError?'alert':'status'}">${e(message)}</p><a class="button" href="/">Back to the app</a></section>`);
